/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoProject;

import org.junit.Test;

import toDoProject.MainClass;

import static org.junit.Assert.*;

public class MainClassTest {
    @Test public void main() {
        MainClass classUnderTest = new MainClass();
        
        classUnderTest.main(null);
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.main("teste aaa"));
    }
}
