/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoProject;

import org.junit.Test;

import toDoProject.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void main() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.main("teste aaa"));
    }
}
