/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoProject;

public class MainClass {
    public static void main(String[] string) {
        System.out.println("Hello");
    }
}